//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class appoinmentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public appoinmentInfo()
        {
            this.doctorInfoes = new HashSet<doctorInfo>();
        }
    
        public int ap_id { get; set; }
        public int userid { get; set; }
        public Nullable<System.DateTime> appointmentDate { get; set; }
        public Nullable<System.TimeSpan> appointmentTime { get; set; }
    
        public virtual userLogin userLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doctorInfo> doctorInfoes { get; set; }
    }
}
