//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctorInfo
    {
        public int doctorId { get; set; }
        public string doctorName { get; set; }
        public string appointmentDetails { get; set; }
        public int ap_id { get; set; }
    
        public virtual appoinmentInfo appoinmentInfo { get; set; }
    }
}
