//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_9f24e4_voywellnessEntities : DbContext
    {
        public db_9f24e4_voywellnessEntities()
            : base("name=db_9f24e4_voywellnessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment_Status> Appointment_Status { get; set; }
        public virtual DbSet<Register_Appointment> Register_Appointment { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
