//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserArName { get; set; }
        public string UserFullName { get; set; }
        public string Password { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string Email { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> FK_BranchId { get; set; }
        public Nullable<int> FK_CustomerID { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<bool> ISHide { get; set; }
        public Nullable<int> Allow_Delete { get; set; }
        public Nullable<int> Allow_Edit { get; set; }
        public Nullable<int> Allow_Select { get; set; }
        public Nullable<int> FK_Trainer_Id { get; set; }
        public Nullable<int> Is_Trainer { get; set; }
    }
}
